Issue/76888
BeAPI/bea-content-sync-fusion pull request #162
Opened 2024-11-22 09:18 UTC by tyffany-robbes

76888 - fix errors 10 & 11 - ensures variables are not empty arrays before use

2024-11-22 17:39 UTC, petitphp requested changes
Merci pour la PR. J'ai laissé quelques commentaires pour corriger un bug et améliorer le sens du code dans une condition.

Il faudra penser à appliquer les coding standard sur le code PHP aussi.

2024-11-22 17:39 UTC, petitphp commented on classes/addons/gutenberg.php
> +				}
Cette partie devrait être dans le `foreach`.

Le `isset( $local_id )` fait doublon avec le `! empty( $local_id )` et peut-être supprimé. La variable `$local_id` sera forcément rempli et le `empty` gère le cas où `$local_id` est `null`.

2024-11-22 17:39 UTC, petitphp commented on classes/addons/gutenberg.php
> +				if ( !empty( $attributes['ids'] ) ) {
Attention au coding standard dans cette PR. Ici par exemple, il manque un espace entre le `!` et le `empty`.

2024-11-22 17:39 UTC, petitphp commented on classes/addons/yoast-seo.php
> +		if ( ! empty( $fb_image_meta ) && isset( $fb_image_meta[0] ) ) {
Ici, on pourrait utiliser `is_array( xxx )` à la place de `! empty( xxx )` étant donné que l'on s'attend à travailler avec  un tableau.

Idem pour le cas de `$twitter_image_meta`.

2024-11-28 10:47 UTC, tyffany-robbes commented
Merci @petitphp pour tes retours !
J'ai fait les corrections. Tu saurais me dire pourquoi les checks sont notés sur failed ? Des problèmes de version visiblement. Y'a un truc que j'ai pas fait correctement ?

2024-11-28 15:22 UTC, tyffany-robbes commented
@petitphp le point qui manquait a été ajouté :) désolée pour l'oubli

2024-11-28 15:48 UTC, petitphp approved these changes
C'est bon pour moi.

2024-11-29 14:00 UTC, merged